version: '3.9'

services:

  # App
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.app
    container_name: frontend
    hostname: frontend
    ports:
      - 5600:5600
    restart: always