version: '3.9'

services:

  # Api
  catalog_api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    container_name: catalog_api
    hostname: catalog_api
    ports:
      - 5601:5600
    restart: always

  catalog_node_01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: catalog_node_01
    hostname: catalog_node_01
    environment:
      - node.name=catalog_node_01
      - cluster.name=catalog_cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200